"""lucky weapon for warriors and dwarves

Revision ID: 00d9c5852cda
Revises: 928c312fe082
Create Date: 2021-10-20 14:31:31.304436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d9c5852cda'
down_revision = '928c312fe082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('lucky_weapon', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'lucky_weapon')
    # ### end Alembic commands ###
