"""inventory and proficient_weapons

Revision ID: 928c312fe082
Revises: 38dc5190666a
Create Date: 2021-10-18 11:46:22.842258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928c312fe082'
down_revision = '38dc5190666a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('inventory', sa.String(length=128), nullable=True))
    op.add_column('characters', sa.Column('proficient_weapons', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'proficient_weapons')
    op.drop_column('characters', 'inventory')
    # ### end Alembic commands ###
