"""added dead, curses, current_hp and deity fields to Character model

Revision ID: e6f70b021712
Revises: 00d9c5852cda
Create Date: 2021-10-22 11:07:01.981763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f70b021712'
down_revision = '00d9c5852cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('current_hp', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('lucky_spell', sa.String(length=64), nullable=True))
    op.add_column('characters', sa.Column('dead', sa.Boolean(), nullable=True))
    op.add_column('characters', sa.Column('curses', sa.String(length=128), nullable=True))
    op.add_column('characters', sa.Column('deity', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'deity')
    op.drop_column('characters', 'curses')
    op.drop_column('characters', 'dead')
    op.drop_column('characters', 'lucky_spell')
    op.drop_column('characters', 'current_hp')
    # ### end Alembic commands ###
