birthsigns = {
    1: ("Hiver rigoureux", "Tous les jets d’attaque"),
    2: ("Le taureau", "Jets d’attaque au corps à corps"),
    3: ("Jour de chance", "Jets d’attaque à distance"),
    4: ("Élevé par les loups", "Jets d’attaque à mains nues"),
    5: ("Conçu à cheval", "Jets d’attaque montée"),
    6: ("Né sur le champ de bataille", "Jets de dégâts"),
    7: ("Voie de l’ours", "Jets de dégâts au corps à corps"),
    8: ("Œil de faucon", "Jets de dégâts à distance"),
    9: ("Chasseur en meute", "Jets d’attaque et dégâts avec arme de départ niveau 0"),
    10: (
        "Né dans l’atelier",
        "Tests de compétence (y compris les compétences de voleur)",
    ),
    11: ("Ruse du renard", "Détecter/désamorcer les pièges"),
    12: ("Trèfle à quatre feuilles", "Trouver les passages secrets"),
    13: ("Septième fils", "Tests d’incantation"),
    14: ("La tempête déchaînée", "Dégâts des sorts"),
    15: ("Cœur vertueux", "Tests pour Repousser les impies"),
    16: ("Survivant de la peste", "Soins magiques*"),
    17: ("Bon présage", "Jets de sauvegarde"),
    18: ("Ange gardien", "Jets de sauvegarde pour échapper aux pièges"),
    19: ("Mordu par une araignée", "Jets de sauvegarde contre le poison"),
    20: ("Frappé par la foudre", "Jets de sauvegarde de Réflexes"),
    21: ("Survivant d’une famine", "Jets de sauvegarde de Vigueur"),
    22: ("A résisté à la tentation", "Jets de sauvegarde de Volonté"),
    23: ("Maison protégée", "Classe d’Armure"),
    24: ("Vitesse du cobra", "Initiative"),
    25: ("Récolte abondante", "Points de vie (s’applique à chaque niveau)"),
    26: ("Bras du guerrier", "Tables de coups critiques**"),
    27: ("Demeure maudite", "Jets de corruption"),
    28: ("L’étoile brisée", "Maladresses**"),
    29: ("Chant d’oiseau", "Nombre de langues"),
    30: ("Enfant sauvage", "Vitesse (chaque +1/-1 = mouvement +1,5 m/-1,5 m)"),
}
