equipment = {
    1: ("Bougie", "1 pc"),
    2: ("Chaîne 3m", "30 po"),
    3: ("Coffre, vide", "2 po"),
    4: ("Corde, 15 m", "25 pc"),
    5: ("Craie, 1 morceau", "1 pc"),
    6: ("Eau bénite, 1 fiole**", "25 po"),
    7: ("Flasque, vide", "3 pc"),
    8: ("Gourde", "5 pa"),
    9: ("Grappin", "1 po"),
    10: ("Huile, 1 flasque***", "2 pa"),
    11: ("Lanterne", "10 po"),
    12: ("Marteau, petit", "5 pa"),
    13: ("Miroir de poche", "10 po"),
    14: ("Outils de voleur", "25 po"),
    15: ("Perche, 3 m", "15 pc"),
    16: ("Pied-de-biche", "2 po"),
    17: ("Pointe en fer, unité", "1 pa"),
    18: ("Rations, par jour", "5 pc"),
    19: ("Sac, grand", "12 pc"),
    20: ("Sac, petit", "8 pc"),
    21: ("Sac à dos", "2 po"),
    22: ("Silex & amadou", "15 pc"),
    23: ("Symbole sacré", "25 po"),
    24: ("Torche, unité", "1 pc"),
}
