fumbles = {
    0: "Vous ratez complètement votre attaque mais ne provoquez miraculeusement aucun autre dégât.",
    1: "Votre attaque maladroite fait de vous la risée du groupe mais ne provoque aucun autre dégât.",
    2: "Vous trébuchez mais pouvez vous rattraper si vous réussissez un jet de sauvegarde de Réflexes DD 10, faute de quoi vous passez le round suivant à terre.",
    3: "Votre arme vous échappe des mains. Vous la rattrapez promptement, mais votre prise n’est plus optimale. Vous subissez une pénalité de -2 sur votre prochain jet d’attaque.",
    4: "Votre arme est endommagée : la corde de l’arc se brise, la garde de l’épée se détache ou le mécanisme de l’arbalète s’enraye. L’arme peut être réparée en 10 mn de travail mais est inutilisable pour le moment.",
    5: "Vous trébuchez et tombez, perdant cette action. Vous êtes à terre et devrez utiliser une action pour vous relever au prochain round.",
    6: "Votre arme se prend dans votre armure. Vous devez passer le prochain round à la dégager. De plus, votre bonus d’armure est réduit de 1 tant que vous n’aurez pas passé 10 mn à réajuster les sangles et attaches emmêlées.",
    7: "Vous lâchez votre arme. Vous devez la ramasser ou en dégainer une autre lors de votre prochaine action.",
    8: "Vous frappez votre arme accidentellement sur un objet solide et inamovible (un rocher, un mur ou même le sol). Les armes courantes sont détruites ; les armes magiques ne sont pas affectées.",
    9: "Vous êtes déséquilibré et vous offrez une ouverture à vos adversaires. Le prochain ennemi qui vous attaque bénéficie d’un bonus de +2 à son jet d’attaque.",
    10: "Vous auriez dû entretenir votre armure ! Ses jointures se grippent et vous immobilisent. Vous ne pouvez ni vous déplacer ni attaquer pendant 1d3 rounds. Les personnages sans armure ne sont pas affectés.",
    11: "Votre attaque mal maîtrisée vous déséquilibre. Vous subissez un malus de -4 à votre prochaine attaque.",
    12: "Vous frappez par inadvertance un de vos alliés à portée, déterminé aléatoirement. Effectuez un jet d’attaque contre celui-ci avec le même dé que celui que vous venez d’employer.",
    13: "Vous trébuchez et chutez violemment, encaissant 1d3 points de dégâts sur le coup. Vous êtes à terre et devez consacrer votre prochaine action à vous relever.",
    14: "Telle une tortue retournée, vous glissez et atterrissez sur le dos, gigotant en tous sens, incapable de vous redresser. Vous devez combattre en étant à terre au prochain round avant de pouvoir reprendre votre équilibre et vous relever.",
    15: "Vous réussissez, on ne sait comment, à vous blesser vous-même, subissant des dégâts normaux.",
    16: "Vous vous frappez accidentellement et subissez des dégâts normaux +1 point supplémentaire.  De plus, vous tombez sur le dos en étant incapable de vous redresser, à moins de réussir un test d’Agilité DD16.",
}
