occupations = {
    1: ("Alchimiste", "Bâton", "Huile, 1 flasque"),
    2: ("Apiculteur", "Bâton", "Pot de miel"),
    3: ("Apprenti mage" "Dague", "Grimoire noir"),
    4: ("Armurier" "Marteau (comme gourdin)", "Heaume en fer"),
    5: ("Astrologue", "Dague", "Longue-vue"),
    6: ("Barbier", "Rasoir (comme dague)", "Ciseaux"),
    7: ("Bedeau", "Bâton", "Symbole sacré"),
    8: ("Berger", "Bâton", "hien de berger**"),
    9: ("Boucher", "Hachoir (comme hachette)", "Tranche de viande"),
    10: ("Bouffon", "Fléchette", "Vêtements de soie"),
    12: ("Bûcheron", "Hachette", "Fagot de bois"),
    11: ("Bûcheron", "Hachette", "Fagot de bois"),
    13: ("Bûcheron", "Hachette", "Fagot de bois"),
    14: ("Chaman", "Masse", "Herbes, 500 g"),
    15: ("Charron", "Gourdin", "Charrette à bras***"),
    16: ("Chasseur", "Arc court", "Peau de cerf"),
    17: ("Chasseur", "Arc court", "Peau de cerf"),
    18: ("Collecteur d’impôt", "Épée longue", "100 pc"),
    19: ("Contrebandier", "Fronde", "Sac étanche"),
    20: ("Cordier", "Couteau (comme dague)", "Corde, 30 m"),
    21: ("Cordonnier", "Poinçon (comme dague)", "Chausse-pied"),
    22: ("Coupeur de bourse", "Dague", "Petit coffre"),
    23: ("Diseur de bonne aventure", "Dague", "Jeu de tarot"),
    24: ("Docker", "Perche (comme bâton)", "1 livre de JdR en retard"),
    25: ("Dresseur", "Gourdin", "Poney"),
    26: ("Écuyer", "Épée longue", "Heaume en acier"),
    27: ("Écuyer", "Épée longue", "Heaume en acier"),
    28: ("Elfe artisan", "Bâton", "Argile, 500 g"),
    29: ("Elfe avocat", "Plume (comme fléchette)", "Livre"),
    30: ("Elfe cirier", "Ciseaux (comme dague)", "Chandelles, 20"),
    31: ("Elfe fauconnier", "Dague", "Faucon"),
    32: ("Elfe forestier", "Bâton", "Herbes, 500 g"),
    33: ("Elfe forestier", "Bâton", "Herbes, 500 g"),
    34: ("Elfe navigateur", "Arc court", "Longue-vue"),
    35: ("Elfe sage", "Dague", "Parchemin et plume"),
    36: ("Elfe sage", "Dague", "Parchemin et plume"),
    37: ("Elfe souffleur de verre", "Marteau (comme gourdin)", "Perles de verre"),
    38: ("Esclave", "Gourdin", "Caillou de forme bizarre"),
    39: ("Escroc", "Dague", "Cape de qualité"),
    40: ("Excavateur", "Pelle (comme bâton)", "Poussière fine, 500 g"),
    41: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    42: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    43: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    44: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    45: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    46: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    47: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    48: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    49: ("Fermier*", "Fourche (comme lance)", "Poule**"),
    50: ("Forgeron", "Marteau (comme gourdin)", "Pinces en acier"),
    51: ("Fossoyeur", "Pelle (comme bâton)", "Truelle"),
    52: ("Fossoyeur", "Pelle (comme bâton)", "Truelle"),
    53: ("Fromager", "Matraque (comme bâton)", "Fromage puant"),
    54: ("Gamin des rues", "Bout de bois (comme gourdin)", "Sébile"),
    55: ("Garde de caravane", "Épée courte", "Drap, 1 m"),
    56: ("Guérisseur", "Gourdin", "Eau bénite, 1 fiole"),
    57: ("Halfelin bohémien", "Fronde", "Poupée vaudou"),
    58: ("Halfelin gantier", "Poinçon (comme dague)", "Gants, 4 paires"),
    59: ("Halfelin marin", "Couteau (comme dague)", "Voile, 2 m"),
    60: ("Halfelin mercier", "Ciseaux (comme dague)", "Costumes, 3 ensembles"),
    61: ("Halfelin négociant", "Épée courte", "20 pa"),
    62: ("Halfelin teinturier", "Bâton", "Tissu, 3 m"),
    63: ("Halfelin teinturier", "Bâton", "Tissu, 3 m"),
    64: ("Halfelin usurier", "Épée courte", "5 po, 10 pa, 200 pc"),
    65: ("Halfelin vagabond", "Gourdin", "Coupelle de mendiant"),
    66: ("Halfelin volailler", "Hachette", "Viande de poulet, 2 kg"),
    67: ("Herboriste", "Gourdin", "Herbes, 500 g"),
    68: ("Hors-la-loi", "Épée", "courte Armure de cuir"),
    69: ("Joaillier", "Dague", "Gemmes valant 20 po"),
    70: ("Joueur", "Gourdin", "Dés"),
    71: ("Maraîcher", "Couteau (comme dague)", "Fruit"),
    72: ("Marchand", "Dague", "4 po, 14 pa, 27 pc"),
    73: ("Mendiant", "Gourdin", "Fromage"),
    74: ("Mendiant de guilde", "Fronde", "Béquilles"),
    75: ("Mendiant de guilde", "Fronde", "Béquilles"),
    76: ("Ménestrel", "Dague", "Ukulélé"),
    77: ("Mercenaire", "Épée longue", "Armure de peau"),
    78: ("Meunier/Boulanger", "Gourdin", "Farine, 500 g"),
    79: ("Nain apothicaire", "Matraque (comme bâton)", "Flacon en acier"),
    80: ("Nain coffretier", "Burin (comme dague)", "Bois, 5 kg"),
    81: ("Nain éleveur", "Bâton", "Truie**"),
    82: ("Nain forgeron", "Marteau (comme gourdin)", "Mithril, 30 g"),
    83: ("Nain maçon", "Marteau", "Pierre, 5 kg"),
    84: ("Nain maçon", "Marteau", "Pierre, 5 kg"),
    85: ("Nain mineur", "Pioche (comme gourdin)", "Lanterne"),
    86: ("Nain mineur", "Pioche (comme gourdin)", "Lanterne"),
    87: ("Nain myciculteur", "Pelle (comme bâton)", "Sacoche"),
    88: ("Nain ratier", "Gourdin", "Filet"),
    89: ("Noble", "Épée longue", "Anneau d’or (10 po)"),
    90: ("Orphelin", "Gourdin", "Poupée de chiffon"),
    91: ("Palefrenier", "Bâton", "Bride"),
    92: ("Scribe", "Fléchette", "Parchemin, 10 feuilles"),
    93: ("Serrurier", "Dague", "Outils de précision"),
    94: ("Serviteur", "Bâton", "Médaillon"),
    95: ("Soldat", "Lance", "Bouclier"),
    96: ("Tisserand", "Dague", "Vêtements de qualité"),
    97: ("Tonnelier", "Pied-de-biche (comme gourdin)", "Tonneau"),
    98: ("Trappeur", "Fronde", "Fourrure de blaireau"),
    99: ("Trappeur", "Fronde", "Fourrure de blaireau"),
    100: ("Vidangeur de latrines", "Truelle (comme dague)", "Sac d’excréments"),
}
