w1 = [
    "Agrandissement",
    "Appel de familier",
    "Bouclier magique",
    "Charme-personne",
    "Compréhension des langues",
    "Contact glacial",
    "Corde enchantée",
    "Couleurs dansantes",
    "Détection de la magie*",
    "Feuille morte",
    "Invocation d’animaux",
    "Invoquer un patron**",
    "Lecture de la magie",
    "Lier un patron**",
    "Mains brûlantes",
    "Masque mystique d’Ekim",
    "Mur de force",
    "Nuage étouffant",
    "Pattes d’araignées",
    "Portail enchanté",
    "Projectile magique",
    "Réparer",
    "Runes des mortels",
    "Sommeil",
    "Tour de magie",
    "Ventriloquie",
    "(Sort de Patron)***",
]

w2 = [
    "Affinité arcanique",
    "Bâton de mage",
    "Bouche magique",
    "Compagnon invisible",
    "Convocation de monstre",
    "Détection du mal*",
    "Effroi",
    "Force",
    "Fracassement",
    "Image miroir",
    "Invisibilité",
    "Lévitation",
    "Localisation d’objet",
    "Manteau d’épines de Nythuul",
    "Oubli",
    "Ouverture",
    "Perception extra-sensorielle (PES)",
    "Phantasme",
    "Rayon affaiblissant",
    "Rayon brûlant",
    "Résistance au feu",
    "Toile d’araignée",
    "Voir l’invisible",
    "(Sort de Patron)***",
]

w3 = [
    "Boule de feu",
    "Bourrasque",
    "Champion éternel",
    "Concoction de potion",
    "Consulter les esprits",
    "Convocation de démon",
    "Dissipation de la magie",
    "Éclair",
    "Écriture de la magie",
    "Hâte",
    "Limier occulte",
    "Maelström entropique d’Emirikol",
    "Magie des épées",
    "Paralysie*",
    "Pétrification",
    "Phase planaire",
    "Ralentissement",
    "Respiration aquatique",
    "Rune des fées",
    "Soumission*",
    "Souffle de vie",
    "Transfert",
    "Vol",
    "(Sort de Patron)***",
]

w4 = [
    "Aide méthodique de Lokerimon",
    "Contrôle de la glace" "Contrôle du feu",
    "Métamorphose",
    "Sens de mage",
    "Transmutation de la terre",
]

w5 = [
    "Champignons féconds d’Hepsoj",
    "Chasseur infaillible de Lokerimon",
    "Duplication",
    "Purge mentale",
    "Rempart magique",
]


wizard_spells = {k: v for k, v in zip(range(1, 6), [w1, w2, w3, w4, w5])}
